### ISSUE TITLE
Accesing objects properties

### ISSUE THREAD

**Issue by mbalestrini** [HaxeFoundation/hscript#10]
I wasn't able to access object properties (getters, setters) in my scripts, just object fields. I had to change Interp.get method to use Reflect.getProperty() instead of Reflect.field().
Is this on purpose because of performance differences between those two methods?

**Comment by DjPale** [comment]
:+1: vote for fixing this, started experimenting with this and came to the conclusion that it didn't work. Discovered this issue afterwards. Also not seeing why fixing this should be a big issue.

**Comment by ncannasse** [comment]
I'm mostly worried about having such a breaking change without people knowing about it.

**Comment by TheSHEEEP** [comment]
I must also say I am unsure as to how this would be a breaking change.

In the documentation it says for getProperty:  
" If the field is not a property, this function behaves like Reflect.field, but might be slower."

So it has extended functionality, solves crash errors, but might be a little slower.
Since functionality + crash solving is clearly more important than a minor speed impact, I see no reason not to implement this.
