### ISSUE TITLE
hl.Bytes types get mangled

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/hscript#125]
I'm using hl.Bytes to represent pointers in an external library (if there is a better way, let me know).  

When I use them as variables in hscript, somehow, when setting / getting them using the reflection system, they come back with some kind of indirection wrapped on them.

I've looked through the depths but I can't find the spot where something is going wrong.  I've wrapped them in another class to fix the problem for now, but at some point I plan on looking to find the bug, because I believe it's with the reflection system in hashlink not hscript.  But the problem shows up when using the types in hscript.

**Comment by ncannasse** [comment]
hl.Bytes being not a Dynamic type, everytime we need to cast a Dynamic to hl.Bytes then it will be wrapped with hl_dynamic that carry its original type (hl.Bytes) + the actual pointer. The same will happen with a native abstract or other native types not being dynamic.

Usually when you cast back from Dynamic to hl.Bytes, you'll get the pointer again after a runtime type check. But in some cases we can't make the cast (for example if you cast a NativeArray<Dynamic> to NativeArray<hl.Bytes> it will not cast the content of the Array). In these cases only, you can get Access Violations are other hard crash errors because of the mismatch between what the VM thinks and what the values are.

In HScript you should be in full Dynamic mode so things should be consistent. The issues should be more with interactions with native code or unsafe casts of Arrays such as above.

**Comment by onehundredfeet** [comment]
Makes sense.  Thanks for the explanation.  Sounds like this is a hashlink thing more than a hscript thing.  It also sounds like something unlikely to get fixed due to the complexity.  I wish there was something that let me know the types were unsupported, but I'm not sure how.  I'll close this out.
